import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Load the Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Exclusive Safaris",
  description: "Generated by GMBNO Studios",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="font-poppins">{children}</body>
    </html>
  );
}
